### ISSUE TITLE
Angular component

### ISSUE THREAD

**Issue by chuksgpfr** [muhammederdem/vue-interactive-paycard#10]
Although this is not an issue related to the package.

I will love to use this package with my angular component. or plain Javascript.

**Comment by muhammederdem** [comment]
Look at this  [tweet](https://twitter.com/ngbs_show/status/1189012309685002240?s=20)
I will create for pure javascript soon

**Comment by tenkmilan** [comment]
Is there a public repo for the created Angular version?

**Comment by milantenk** [comment]
I created an Angular alternative for this library. It can be found here:
https://github.com/milantenk/ngx-interactive-paycard
