### ISSUE TITLE
save button

### ISSUE THREAD

**Issue by diomed** [muhammederdem/vue-interactive-paycard#15]
can you have save button?
so we can save generated card as image [png/svg/jpg]

or pdf maybe...

possibilities... possibilities....

**Comment by muhammederdem** [comment]
I don't think we'll need that. :) It's payment form. Clients won't want to. It's suspicious.

**Comment by diomed** [comment]
you are absolutely right - as far as credit cards are concerned.
however, I have different plans with this little project:

Could you possibly commit these changes to my fork of your repository?
https://github.com/diomed/vue-interactive-paycard

I'd appreciate it very much.

**Comment by muhammederdem** [comment]
Can you create a pull request?

**Comment by diomed** [comment]
no. I don't know enough of javascript for that.

am just a newb

**Comment by muhammederdem** [comment]
Sorry I misunderstood. You can pull changes. Github syncs both repository.

**Comment by muhammederdem** [comment]
you can find how to pull my changes [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by diomed** [comment]
I dont understand. where can I find your changes made for what I requested?
