### ISSUE TITLE
 compress for image to minimum possible size

### ISSUE THREAD

**Issue by LeoLiu1209** [muhammederdem/vue-interactive-paycard#19]
I used [Optimizilla ](https://imagecompressor.com/)to compress the images for about 30~50% for each and hardly tell the difference. :100: 
The image i put it on my [GDrive](https://drive.google.com/drive/folders/1T0_RcS82dSe-3hXoQUVPkykA0nawCZWj?usp=sharing), if u think is helpful, i would love to create a PR  for this.

**Comment by muhammederdem** [comment]
I'm thinking about something else for images. I'm on it. Thank you.

**Comment by LeoLiu1209** [comment]
ok!!!!
Looking forward for the new changing :+1: , btw i would close this issue.
