### ISSUE TITLE
Looking forward to npm component installation

### ISSUE THREAD

**Issue by LaravDev** [muhammederdem/vue-interactive-paycard#30]
This would be an awesome component to install, just looking forward if you are still working on it... in any case, great job!

**Comment by guastallaigor** [comment]
+1 for this, I can help if you want

**Comment by GSabadini** [comment]
@LaravDev https://github.com/guastallaigor/vue-paycard

**Comment by LaravDev** [comment]
> @LaravDev https://github.com/guastallaigor/vue-paycard

Wow! Thanks! And thanks again!
