### ISSUE TITLE
numbers & letters - quick question

### ISSUE THREAD

**Issue by diomed** [muhammederdem/vue-interactive-paycard#8]
hi.

how to enable numbers and letters in my fork of your credit card form?

I need it as generator of  something else.

**Comment by diomed** [comment]
btw. this app is super cool 👍 😻

**Comment by ackvf** [comment]
@diomed would be nice if you wrote what you discovered.

**Comment by diomed** [comment]
I've discovered that creator of this repo doesn't care about my question, nor about my feedback
I've also discovered I have great friends who advised me that I just simply replace with this line:

`otherCardMask: "XXXXXXXXXXX",`

and everything shall work fine for me.

**Comment by muhammederdem** [comment]
Hi @diomed  sorry for delay. I did not understand the problem. If you can give me some more details and I would love to help you

**Comment by diomed** [comment]
my problem is solved. friends told me that all I had to do to have letters and numbers, is to change # into X

**Comment by muhammederdem** [comment]
Okay, that's great.

**Comment by diomed** [comment]
maybe you could add more backgrounds somehow - or have an option to add unsplash image id so one can change background, and pull it via unsplash id.

just a thought.

**Comment by muhammederdem** [comment]
yes, I was thinking custom background images. I will do it. thanks
